### PR TITLE
Properly order pipeline-latest-release even with RC

### PR DESCRIPTION
**Pull request by chmouel**
and increase MAX_SHIFT by a lot since there could be a lot of RCs

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/cli/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by piyush-garg** [comment]
We can keep the max_shift to same as running a very old version pipeline will not make sense and also better if it fails as it will be a nice reminder to do the midstream release.

**Comment by chmouel** [comment]
fair enough @piyush-garg just saw your comment, i think we can have a patch to keep 1 then...

**Pull request merged**
